on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'feature/actions-test'
  pull_request:
    branches-ignore:
      - 'feature/actions-test'

permissions:
  contents: read

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [macos-15, macos-14, macos-13]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install dependencies
      run: |
        brew install libsodium
    - name: Compile 
      run: |
        ./configure
        make -C build
    - name: Test 
      run: |
        otool -L build/vpnserver
        .ci/memory-leak-test.sh

